class_name GameConstants
extends Node

const TILE_SIZE := 16
const CHUNK_SIZE := 16
const CHUNK_PIXEL_SIZE := CHUNK_SIZE * TILE_SIZE

const PLAYER_SPEED := 100.0
const PLAYER_SPRINT_SPEED := 160.0
const PLAYER_ACCELERATION := 800.0
const PLAYER_FRICTION := 800.0

const MAX_HEALTH := 5
const MAX_STAMINA := 100.0
const MAX_HUNGER := 100.0
const MAX_THIRST := 100.0

const HUNGER_DRAIN_RATE := 0.033
const THIRST_DRAIN_RATE := 0.055
const STAMINA_REGEN_RATE := 2.0
const STAMINA_SPRINT_COST := 20.0
const STAMINA_GATHER_COST := 5.0

const DAY_LENGTH_MINUTES := 24.0
const REAL_TIME_SCALE := 2.0

const INVENTORY_MAX_SLOTS := 30
const ITEM_DROP_PERCENTAGE_ON_DEATH := 0.5

const INTERACT_RANGE := 40.0
const ATTACK_RANGE := 35.0
const GATHER_RANGE := 45.0
